# docker-compose.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MIDEND_PORT: $MIDEND_PORT
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
    ports:
      - $MIDEND_PORT:$MIDEND_PORT
    env_file:
      - ./.env
    restart: always
